git:
  depth: 10
notifications:
  email:
     on_success: always
     on_failure: always
language: csharp
python: '2.7'
install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get -q update && sudo apt-get -q -y --no-install-recommends install g++ g++-multilib; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then wget -O qt-opensource-linux-x64-5.6.2.run https://download.qt.io/official_releases/qt/5.6/5.6.2/qt-opensource-linux-x64-5.6.2.run; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then chmod +x qt-opensource-linux-x64-5.6.2.run; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then ./qt-opensource-linux-x64-5.6.2.run --script CI/qt-installer-noninterative-562.qs -platform minimal; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then wget -O qt-opensource-mac-x64-clang-5.6.2.dmg https://download.qt.io/official_releases/qt/5.6/5.6.2/qt-opensource-mac-x64-clang-5.6.2.dmg; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then defaults write com.apple.frameworks.diskimages skip-verify TRUE; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then hdiutil attach qt-opensource-mac-x64-clang-5.6.2.dmg; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then ls /Volumes; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then hdiutil info; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then /Volumes/qt-opensource-mac-x64-clang-5.6.2/qt-opensource-mac-x64-clang-5.6.2.app/Contents/MacOS/qt-opensource-mac-x64-clang-5.6.2 --script CI/qt-installer-noninterative-562.qs; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then hdiutil detach qt-opensource-mac-x64-clang-5.6.2; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then defaults write com.apple.frameworks.diskimages skip-verify FALSE; fi
  - wget 'https://ci.appveyor.com/api/projects/markfinal/buildamation/artifacts/bam.tar?branch=master&job=Image%3A%20Visual%20Studio%202017' -O /tmp/bam.tar
  - mkdir -p /tmp/BuildAMation
  - tar xf /tmp/bam.tar -C /tmp/BuildAMation
before_script:
  - dotnet --version
env:
  global:
    - EXTRA_TEST_ARGS="--C.bitdepth=64 -t Qt5Test1"
matrix:
  include:
  - os: linux
    dist: trusty
    mono: none
    dotnet: 2.1.401
    name: Ubuntu 14 (GCC 4.8) Native
    env:
      - BAM_BUILD_MODE=Native
      - BAM_TOOLCHAIN_NAME=Gcc
      - BAM_TOOLCHAIN_VERSION=4.8
  #- os: linux
  #  dist: trusty
  #  mono: none
  #  dotnet: 2.1.401
  #  name: Ubuntu 14 (GCC 4.8) MakeFile
  #  env:
  #    - BAM_BUILD_MODE=MakeFile
  #    - BAM_TOOLCHAIN_NAME=Gcc
  #    - BAM_TOOLCHAIN_VERSION=4.8
  #- os: osx
  #  osx_image: xcode10.2
  #  mono: none
  #  dotnet: 2.1.401
  #  name: MacOS (Xcode 10.2) Native
  #  env:
  #    - BAM_BUILD_MODE=Native
  #    - BAM_TOOLCHAIN_NAME=Clang
  #    - BAM_TOOLCHAIN_VERSION=Xcode10
  #    - EXTRA_TEST_ARGS="-T WindowLibrary --C.bitdepth=64" # 32-bit support removed
  #    - TRAVIS_PREFIX=travis_wait # because the VulkanTriangle test seems to cause travis to appear to stop responding
  #- os: osx
  #  osx_image: xcode10.2
  #  mono: none
  #  dotnet: 2.1.401
  #  name: MacOS (Xcode 10.2) MakeFile
  #  env:
  #    - BAM_BUILD_MODE=MakeFile
  #    - BAM_TOOLCHAIN_NAME=Clang
  #    - BAM_TOOLCHAIN_VERSION=Xcode10
  #    - EXTRA_TEST_ARGS="-T WindowLibrary --C.bitdepth=64" # 32-bit support removed
  #    - TRAVIS_PREFIX=travis_wait # because the VulkanTriangle test seems to cause travis to appear to stop responding
  #- os: osx
  #  osx_image: xcode10.2
  #  mono: none
  #  dotnet: 2.1.401
  #  name: MacOS (Xcode 10.2) Xcode
  #  env:
  #    - BAM_BUILD_MODE=Xcode
  #    - BAM_TOOLCHAIN_NAME=Clang
  #    - BAM_TOOLCHAIN_VERSION=Xcode10
  #    - EXTRA_TEST_ARGS="-T WindowLibrary --C.bitdepth=64" # 32-bit support removed
  #    - TRAVIS_PREFIX=travis_wait # because the VulkanTriangle test seems to cause travis to appear to stop responding
  - os: osx
    osx_image: xcode9.4
    mono: none
    dotnet: 2.1.401
    name: MacOS (Xcode 9.4) Native
    env:
      - BAM_BUILD_MODE=Native
      - BAM_TOOLCHAIN_NAME=Clang
      - BAM_TOOLCHAIN_VERSION=Xcode9
  #- os: osx
  #  osx_image: xcode9.4
  #  mono: none
  #  dotnet: 2.1.401
  #  name: MacOS (Xcode 9.4) MakeFile
  #  env:
  #    - BAM_BUILD_MODE=MakeFile
  #    - BAM_TOOLCHAIN_NAME=Clang
  #    - BAM_TOOLCHAIN_VERSION=Xcode9
  #- os: osx
  #  osx_image: xcode9.4
  #  mono: none
  #  dotnet: 2.1.401
  #  name: MacOS (Xcode 9.4) Xcode
  #  env:
  #    - BAM_BUILD_MODE=Xcode
  #    - BAM_TOOLCHAIN_NAME=Clang
  #    - BAM_TOOLCHAIN_VERSION=Xcode9
  #- os: osx
  #  osx_image: xcode8.3
  #  mono: none
  #  dotnet: 2.1.401
  #  name: MacOS (Xcode 8.3) Native
  #  env:
  #    - BAM_BUILD_MODE=Native
  #    - BAM_TOOLCHAIN_NAME=Clang
  #    - BAM_TOOLCHAIN_VERSION=Xcode8
  #    - EXTRA_TEST_ARGS="-T WindowLibrary -T VulkanTriangle" # Not supported on Xcode older than 9
  #- os: osx
  #  osx_image: xcode8.3
  #  mono: none
  #  dotnet: 2.1.401
  #  name: MacOS (Xcode 8.3) MakeFile
  #  env:
  #    - BAM_BUILD_MODE=MakeFile
  #    - BAM_TOOLCHAIN_NAME=Clang
  #    - BAM_TOOLCHAIN_VERSION=Xcode8
  #    - EXTRA_TEST_ARGS="-T WindowLibrary -T VulkanTriangle" # Not supported on Xcode older than 9
  #- os: osx
  #  osx_image: xcode8.3
  #  mono: none
  #  dotnet: 2.1.401
  #  name: MacOS (Xcode 8.3) Xcode
  #  env:
  #    - BAM_BUILD_MODE=Xcode
  #    - BAM_TOOLCHAIN_NAME=Clang
  #    - BAM_TOOLCHAIN_VERSION=Xcode8
  #    - EXTRA_TEST_ARGS="-T WindowLibrary -T VulkanTriangle" # Not supported on Xcode older than 9
script:
  - source /tmp/BuildAMation/env.sh && $TRAVIS_PREFIX python /tmp/BuildAMation/tests/runtests.py --${BAM_TOOLCHAIN_NAME}.version=${BAM_TOOLCHAIN_VERSION} -c debug -c profile -j0 -d --nodefaultrepo -r . -b $BAM_BUILD_MODE $EXTRA_TEST_ARGS
